#!/usr/bin/env -S perl

use v5.40;
use experimental qw(class declared_refs defer refaliasing);

use DateTime::TimeZone::Zoneinfo qw(timezone);
use Time::Moment                 qw();

use Data::Printer;

@ARGV
    or push @ARGV, 'Europe/Amsterdam';

my $tz = timezone($ARGV[0]);

p $tz->transitions, fulldump => 1;

__END__
